<?php
/*** 
 * playlist-display.php
 * by Wolf I. Butler
 * v. 2.2, Last Updated: 9/14/2022
 * 
 * "Quick" script to display a saved playlist file generated by push-playlist.php
 * The push-playlist script runs on the FPP Show Runner through the scheduler.
 * 
 * This script also uses the playlist.sync file pushed from the show-runner with the 
 * current status and currently-playing sequence/song. It will show the currently playing
 * song if there is one.
 * 
*/

//Just set these, if necessary...
//By default these files are synced using the sync-playlist and sync-status APIs.
define ( 'PLAYLIST', './playlist.json' );  //Playlist
define ( 'SYNC', './playlist.sync' );  //Playlist update time

//Leave the rest alone...

session_start ();   //Using session to cache playlist.

?>
<HTML>
<HEAD>
<meta http-equiv="refresh" content="10">
<style>
    tr:nth-child(even) {background-color: #ddffdd;}
    tr:nth-child(odd) {background-color: #ffdddd;}
    th {
        background-color: #880000;
        color: #ffffff;
    }
    .np {
        background-color: #008800;
        color: #ffffff;
    }
</style>
</HEAD>
<BODY>
<table>
    <thead>
    <tr><th>Song Title</th><th>Artist</th><th>Album</th><th>Run Time</th></tr>
    </thead>
    <tbody>

<?php

if ( ! isset ( $_SESSION['playlist'] ) ) {
    //Load session with playlist...
    $_SESSION['playlist'] = json_decode ( file_get_contents ( PLAYLIST ), TRUE );
    $_SESSION['updateTime'] = date ( 'Y-m-d H:i:s', filectime ( PLAYLIST ) );
}
elseif ( $_SESSION['updateTime'] != date ( 'Y-m-d H:i:s', filectime ( PLAYLIST ) ) ) {
    //Refresh session...
    $_SESSION['playlist'] = json_decode ( file_get_contents ( PLAYLIST ), TRUE );
    $_SESSION['updateTime'] = date ( 'Y-m-d H:i:s', filectime ( PLAYLIST ) );
}

$arrSync = json_decode ( file_get_contents ( SYNC ), TRUE );
if ( $arrSync['status'] == 'playing' ) $nowPlaying = TRUE;
else $nowPlaying = FALSE;

$hFlag = TRUE;
foreach ( $_SESSION['playlist'] as $index => $item ) {
    if ( $nowPlaying && $hFlag ) {
        if ( $item['MediaName'] == $arrSync['song'] ) {
            $hFlag = FALSE;     //Don't highlight dupes.
            echo "<tr>\n";
            echo "<td class=\"np\"><b>Now Playing:<br>".$item['Title']."</b></td>\n";
            echo "<td class=\"np\"><b>".$item['Artist']."</b></td>\n";
            echo "<td class=\"np\"><b>".$item['Album']."</b></td>\n";
            echo "<td class=\"np\"><b>".$item['RunTime']."</b></td>\n";
            echo "</tr>\n";
            continue;    
        }
    }

    echo "<tr>\n";
    echo "<td>".$item['Title']."</td>\n";
    echo "<td>".$item['Artist']."</td>\n";
    echo "<td>".$item['Album']."</td>\n";
    echo "<td>".$item['RunTime']."</td>\n";
    echo "</tr>\n";
}

?>
</tbody>
</table>
<?php
if ( $nowPlaying ) echo "<div align=\"center\">*<em>Now Playing</em> information may be delayed or outdated.</div>\n";
else echo "<div align=\"center\">(Nothing is playing right now. The playlist was last updated: " . $_SESSION['updateTime'] . ") </div>\n";
?>
</BODY>
</HTML>
