<?php
/*** 
 * playlist-display.php
 * by Wolf I. Butler
 * v. 2.0, Last Updated: 08/25/2022
 * 
 * "Quick" script to display a saved playlist file generated by playlist_dump_v2.0.php
 * This works with the playlist-dump script, which generates the playlist as a JSON file.
 * Use to display the playlist on a Web site.
 * 
 * The playlist data must be provided by the Show Runner and uploaded to the designated
 * path below. Currently this is done by the playlist-dump.php script run in the Lead-In
 * section of each sequence on the Show Runner.
 * 
*/

//Just set these...
//By default these files are rsynced from the Show Runner FPP server.
define ( 'PLAYLIST', './playlist.json' );  //Playlist
define ( 'SYNC', './playlist.sync' );  //Playlist update time

//Leave the rest alone...

?>
<HTML>
<HEAD>
<meta http-equiv="refresh" content="15">
<style>
    tr:nth-child(even) {background-color: #ddffdd;}
    tr:nth-child(odd) {background-color: #ffdddd;}
    th {
        background-color: #880000;
        color: #ffffff;
    }
    .np {
        background-color: #008800;
        color: #ffffff;
    }
</style>
</HEAD>
<BODY>
<table>
    <thead>
    <tr><th>Song Title</th><th>Artist</th><th>Album</th><th>Run Time</th></tr>
    </thead>
    <tbody>

<?php

$arrPlaylist = json_decode ( file_get_contents ( PLAYLIST ), TRUE );
$arrSync = json_decode ( file_get_contents ( SYNC ), TRUE );
$updateTime = date ( 'Y-m-d H:i:s', filectime ( PLAYLIST ) );

$i = 0; //Init array index.
$nowPlaying = FALSE;
foreach ( $arrPlaylist as $item ) {
    if ( $item['MediaName'] == $arrSync['song'] ) {
        $nowPlaying = TRUE;
        echo "<tr>\n";
        echo "<td class=\"np\"><b>Now Playing:</b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
        echo "<font size=\"-1\">(" . $arrSync['time'] . " * )</font><br><b>".$item['Title']."</b></td>\n";
        echo "<td class=\"np\"><b>".$item['Artist']."</b></td>\n";
        echo "<td class=\"np\"><b>".$item['Album']."</b></td>\n";
        echo "<td class=\"np\"><b>".$item['RunTime']."</b></td>\n";
        echo "</tr>\n";    
    }
    else {
        echo "<tr>\n";
        echo "<td>".$item['Title']."</td>\n";
        echo "<td>".$item['Artist']."</td>\n";
        echo "<td>".$item['Album']."</td>\n";
        echo "<td>".$item['RunTime']."</td>\n";
        echo "</tr>\n";
    }
}

?>
</tbody>
</table>
<?php
if ( $nowPlaying ) echo "<div align=\"center\">*<em>Now Playing</em> information may be delayed or outdated. Please double-check date and time.</div>\n";
else echo "<div align=\"center\">(Nothing is playing right now. The playlist was last updated: " . $updateTime . ") </div>\n";
?>
</BODY>
</HTML>
